stages:
    - build
    - lint
    - test
    - deploy

composer:
    stage: build
    artifacts:
        name: "$CI_JOB_NAME"
        untracked: true
        expire_in: "2 days"
        paths:
            - vendor/
    only:
        - branches
        - tags
        - pushes
        - merge_requests
    tags:
        - composer
    script:
        - "make composer-version"
        - "make composer-install"
        - "make composer-autoload"

lint:
    stage: lint
    dependencies:
        - composer
    tags:
        - test
    only:
        - branches
        - tags
        - pushes
        - merge_requests
    script:
        - make lint

phpunit:
    stage: test
    dependencies:
        - composer
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - build/logs/junit.xml
            - build/logs/clover.xml
            - build/logs/crap4j.xml
            - build/coverage/
        expire_in: "2 weeks"
    tags:
        - xdebug
        - test
    only:
        - tags
    script:
        - make phpunit
